/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messagefile.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "messagefile.pb-c.h"
void   time_val__init
                     (TimeVal         *message)
{
  static TimeVal init_value = TIME_VAL__INIT;
  *message = init_value;
}
size_t time_val__get_packed_size
                     (const TimeVal *message)
{
  assert(message->base.descriptor == &time_val__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t time_val__pack
                     (const TimeVal *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &time_val__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t time_val__pack_to_buffer
                     (const TimeVal *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &time_val__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TimeVal *
       time_val__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TimeVal *)
     protobuf_c_message_unpack (&time_val__descriptor,
                                allocator, len, data);
}
void   time_val__free_unpacked
                     (TimeVal *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &time_val__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   settimeofday_request__init
                     (SettimeofdayRequest         *message)
{
  static SettimeofdayRequest init_value = SETTIMEOFDAY_REQUEST__INIT;
  *message = init_value;
}
size_t settimeofday_request__get_packed_size
                     (const SettimeofdayRequest *message)
{
  assert(message->base.descriptor == &settimeofday_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t settimeofday_request__pack
                     (const SettimeofdayRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &settimeofday_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t settimeofday_request__pack_to_buffer
                     (const SettimeofdayRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &settimeofday_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SettimeofdayRequest *
       settimeofday_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SettimeofdayRequest *)
     protobuf_c_message_unpack (&settimeofday_request__descriptor,
                                allocator, len, data);
}
void   settimeofday_request__free_unpacked
                     (SettimeofdayRequest *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &settimeofday_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   settimeofday_response__init
                     (SettimeofdayResponse         *message)
{
  static SettimeofdayResponse init_value = SETTIMEOFDAY_RESPONSE__INIT;
  *message = init_value;
}
size_t settimeofday_response__get_packed_size
                     (const SettimeofdayResponse *message)
{
  assert(message->base.descriptor == &settimeofday_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t settimeofday_response__pack
                     (const SettimeofdayResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &settimeofday_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t settimeofday_response__pack_to_buffer
                     (const SettimeofdayResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &settimeofday_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SettimeofdayResponse *
       settimeofday_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SettimeofdayResponse *)
     protobuf_c_message_unpack (&settimeofday_response__descriptor,
                                allocator, len, data);
}
void   settimeofday_response__free_unpacked
                     (SettimeofdayResponse *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &settimeofday_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gettimeofday_request__init
                     (GettimeofdayRequest         *message)
{
  static GettimeofdayRequest init_value = GETTIMEOFDAY_REQUEST__INIT;
  *message = init_value;
}
size_t gettimeofday_request__get_packed_size
                     (const GettimeofdayRequest *message)
{
  assert(message->base.descriptor == &gettimeofday_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gettimeofday_request__pack
                     (const GettimeofdayRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gettimeofday_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gettimeofday_request__pack_to_buffer
                     (const GettimeofdayRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gettimeofday_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GettimeofdayRequest *
       gettimeofday_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GettimeofdayRequest *)
     protobuf_c_message_unpack (&gettimeofday_request__descriptor,
                                allocator, len, data);
}
void   gettimeofday_request__free_unpacked
                     (GettimeofdayRequest *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &gettimeofday_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gettimeofday_response__init
                     (GettimeofdayResponse         *message)
{
  static GettimeofdayResponse init_value = GETTIMEOFDAY_RESPONSE__INIT;
  *message = init_value;
}
size_t gettimeofday_response__get_packed_size
                     (const GettimeofdayResponse *message)
{
  assert(message->base.descriptor == &gettimeofday_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gettimeofday_response__pack
                     (const GettimeofdayResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gettimeofday_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gettimeofday_response__pack_to_buffer
                     (const GettimeofdayResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gettimeofday_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GettimeofdayResponse *
       gettimeofday_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GettimeofdayResponse *)
     protobuf_c_message_unpack (&gettimeofday_response__descriptor,
                                allocator, len, data);
}
void   gettimeofday_response__free_unpacked
                     (GettimeofdayResponse *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &gettimeofday_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   request__init
                     (Request         *message)
{
  static Request init_value = REQUEST__INIT;
  *message = init_value;
}
size_t request__get_packed_size
                     (const Request *message)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t request__pack
                     (const Request *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t request__pack_to_buffer
                     (const Request *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Request *
       request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Request *)
     protobuf_c_message_unpack (&request__descriptor,
                                allocator, len, data);
}
void   request__free_unpacked
                     (Request *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   response__init
                     (Response         *message)
{
  static Response init_value = RESPONSE__INIT;
  *message = init_value;
}
size_t response__get_packed_size
                     (const Response *message)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t response__pack
                     (const Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t response__pack_to_buffer
                     (const Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Response *
       response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Response *)
     protobuf_c_message_unpack (&response__descriptor,
                                allocator, len, data);
}
void   response__free_unpacked
                     (Response *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   x_rpcmessage__init
                     (XRPCMessage         *message)
{
  static XRPCMessage init_value = X_RPCMESSAGE__INIT;
  *message = init_value;
}
size_t x_rpcmessage__get_packed_size
                     (const XRPCMessage *message)
{
  assert(message->base.descriptor == &x_rpcmessage__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t x_rpcmessage__pack
                     (const XRPCMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &x_rpcmessage__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t x_rpcmessage__pack_to_buffer
                     (const XRPCMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &x_rpcmessage__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
XRPCMessage *
       x_rpcmessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (XRPCMessage *)
     protobuf_c_message_unpack (&x_rpcmessage__descriptor,
                                allocator, len, data);
}
void   x_rpcmessage__free_unpacked
                     (XRPCMessage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &x_rpcmessage__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor time_val__field_descriptors[2] =
{
  {
    "tv_sec",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(TimeVal, has_tv_sec),
    offsetof(TimeVal, tv_sec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tv_usec",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(TimeVal, has_tv_usec),
    offsetof(TimeVal, tv_usec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned time_val__field_indices_by_name[] = {
  0,   /* field[0] = tv_sec */
  1,   /* field[1] = tv_usec */
};
static const ProtobufCIntRange time_val__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor time_val__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TimeVal",
  "TimeVal",
  "TimeVal",
  "",
  sizeof(TimeVal),
  2,
  time_val__field_descriptors,
  time_val__field_indices_by_name,
  1,  time_val__number_ranges,
  (ProtobufCMessageInit) time_val__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor settimeofday_request__field_descriptors[1] =
{
  {
    "timeval",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SettimeofdayRequest, timeval),
    &time_val__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned settimeofday_request__field_indices_by_name[] = {
  0,   /* field[0] = timeval */
};
static const ProtobufCIntRange settimeofday_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor settimeofday_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SettimeofdayRequest",
  "SettimeofdayRequest",
  "SettimeofdayRequest",
  "",
  sizeof(SettimeofdayRequest),
  1,
  settimeofday_request__field_descriptors,
  settimeofday_request__field_indices_by_name,
  1,  settimeofday_request__number_ranges,
  (ProtobufCMessageInit) settimeofday_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor settimeofday_response__field_descriptors[2] =
{
  {
    "return_value",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(SettimeofdayResponse, has_return_value),
    offsetof(SettimeofdayResponse, return_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errno_alt",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(SettimeofdayResponse, has_errno_alt),
    offsetof(SettimeofdayResponse, errno_alt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned settimeofday_response__field_indices_by_name[] = {
  1,   /* field[1] = errno_alt */
  0,   /* field[0] = return_value */
};
static const ProtobufCIntRange settimeofday_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor settimeofday_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SettimeofdayResponse",
  "SettimeofdayResponse",
  "SettimeofdayResponse",
  "",
  sizeof(SettimeofdayResponse),
  2,
  settimeofday_response__field_descriptors,
  settimeofday_response__field_indices_by_name,
  1,  settimeofday_response__number_ranges,
  (ProtobufCMessageInit) settimeofday_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gettimeofday_request__field_descriptors[1] =
{
  {
    "stub",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(GettimeofdayRequest, has_stub),
    offsetof(GettimeofdayRequest, stub),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gettimeofday_request__field_indices_by_name[] = {
  0,   /* field[0] = stub */
};
static const ProtobufCIntRange gettimeofday_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor gettimeofday_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GettimeofdayRequest",
  "GettimeofdayRequest",
  "GettimeofdayRequest",
  "",
  sizeof(GettimeofdayRequest),
  1,
  gettimeofday_request__field_descriptors,
  gettimeofday_request__field_indices_by_name,
  1,  gettimeofday_request__number_ranges,
  (ProtobufCMessageInit) gettimeofday_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gettimeofday_response__field_descriptors[3] =
{
  {
    "return_value",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(GettimeofdayResponse, has_return_value),
    offsetof(GettimeofdayResponse, return_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errno_alt",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(GettimeofdayResponse, has_errno_alt),
    offsetof(GettimeofdayResponse, errno_alt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timeval",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(GettimeofdayResponse, timeval),
    &time_val__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gettimeofday_response__field_indices_by_name[] = {
  1,   /* field[1] = errno_alt */
  0,   /* field[0] = return_value */
  2,   /* field[2] = timeval */
};
static const ProtobufCIntRange gettimeofday_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor gettimeofday_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GettimeofdayResponse",
  "GettimeofdayResponse",
  "GettimeofdayResponse",
  "",
  sizeof(GettimeofdayResponse),
  3,
  gettimeofday_response__field_descriptors,
  gettimeofday_response__field_indices_by_name,
  1,  gettimeofday_response__number_ranges,
  (ProtobufCMessageInit) gettimeofday_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor request__field_descriptors[2] =
{
  {
    "settimeofday_request",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Request, request_func_case),
    offsetof(Request, settimeofday_request),
    &settimeofday_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gettimeofday_request",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Request, request_func_case),
    offsetof(Request, gettimeofday_request),
    &gettimeofday_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned request__field_indices_by_name[] = {
  1,   /* field[1] = gettimeofday_request */
  0,   /* field[0] = settimeofday_request */
};
static const ProtobufCIntRange request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Request",
  "Request",
  "Request",
  "",
  sizeof(Request),
  2,
  request__field_descriptors,
  request__field_indices_by_name,
  1,  request__number_ranges,
  (ProtobufCMessageInit) request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response__field_descriptors[2] =
{
  {
    "settimeofday_response",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Response, response_func_case),
    offsetof(Response, settimeofday_response),
    &settimeofday_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gettimeofday_response",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Response, response_func_case),
    offsetof(Response, gettimeofday_response),
    &gettimeofday_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__field_indices_by_name[] = {
  1,   /* field[1] = gettimeofday_response */
  0,   /* field[0] = settimeofday_response */
};
static const ProtobufCIntRange response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response",
  "Response",
  "Response",
  "",
  sizeof(Response),
  2,
  response__field_descriptors,
  response__field_indices_by_name,
  1,  response__number_ranges,
  (ProtobufCMessageInit) response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor x_rpcmessage__field_descriptors[3] =
{
  {
    "request",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(XRPCMessage, message_type_case),
    offsetof(XRPCMessage, request),
    &request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "response",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(XRPCMessage, message_type_case),
    offsetof(XRPCMessage, response),
    &response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time_stamp",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(XRPCMessage, time_stamp),
    &time_val__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned x_rpcmessage__field_indices_by_name[] = {
  0,   /* field[0] = request */
  1,   /* field[1] = response */
  2,   /* field[2] = time_stamp */
};
static const ProtobufCIntRange x_rpcmessage__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor x_rpcmessage__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "xRPCMessage",
  "XRPCMessage",
  "XRPCMessage",
  "",
  sizeof(XRPCMessage),
  3,
  x_rpcmessage__field_descriptors,
  x_rpcmessage__field_indices_by_name,
  1,  x_rpcmessage__number_ranges,
  (ProtobufCMessageInit) x_rpcmessage__init,
  NULL,NULL,NULL    /* reserved[123] */
};
