/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: syscallprot.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "syscallprot.pb-c.h"
void   sys_rpc__x_rpc_message_type__init
                     (SysRpc__XRPCMessageType         *message)
{
  static const SysRpc__XRPCMessageType init_value = SYS_RPC__X_RPC_MESSAGE_TYPE__INIT;
  *message = init_value;
}
size_t sys_rpc__x_rpc_message_type__get_packed_size
                     (const SysRpc__XRPCMessageType *message)
{
  assert(message->base.descriptor == &sys_rpc__x_rpc_message_type__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sys_rpc__x_rpc_message_type__pack
                     (const SysRpc__XRPCMessageType *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sys_rpc__x_rpc_message_type__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sys_rpc__x_rpc_message_type__pack_to_buffer
                     (const SysRpc__XRPCMessageType *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sys_rpc__x_rpc_message_type__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SysRpc__XRPCMessageType *
       sys_rpc__x_rpc_message_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SysRpc__XRPCMessageType *)
     protobuf_c_message_unpack (&sys_rpc__x_rpc_message_type__descriptor,
                                allocator, len, data);
}
void   sys_rpc__x_rpc_message_type__free_unpacked
                     (SysRpc__XRPCMessageType *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sys_rpc__x_rpc_message_type__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sys_rpc__settimeofday_request__timeval__init
                     (SysRpc__SettimeofdayRequest__Timeval         *message)
{
  static const SysRpc__SettimeofdayRequest__Timeval init_value = SYS_RPC__SETTIMEOFDAY_REQUEST__TIMEVAL__INIT;
  *message = init_value;
}
void   sys_rpc__settimeofday_request__timezone__init
                     (SysRpc__SettimeofdayRequest__Timezone         *message)
{
  static const SysRpc__SettimeofdayRequest__Timezone init_value = SYS_RPC__SETTIMEOFDAY_REQUEST__TIMEZONE__INIT;
  *message = init_value;
}
void   sys_rpc__settimeofday_request__init
                     (SysRpc__SettimeofdayRequest         *message)
{
  static const SysRpc__SettimeofdayRequest init_value = SYS_RPC__SETTIMEOFDAY_REQUEST__INIT;
  *message = init_value;
}
size_t sys_rpc__settimeofday_request__get_packed_size
                     (const SysRpc__SettimeofdayRequest *message)
{
  assert(message->base.descriptor == &sys_rpc__settimeofday_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sys_rpc__settimeofday_request__pack
                     (const SysRpc__SettimeofdayRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sys_rpc__settimeofday_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sys_rpc__settimeofday_request__pack_to_buffer
                     (const SysRpc__SettimeofdayRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sys_rpc__settimeofday_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SysRpc__SettimeofdayRequest *
       sys_rpc__settimeofday_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SysRpc__SettimeofdayRequest *)
     protobuf_c_message_unpack (&sys_rpc__settimeofday_request__descriptor,
                                allocator, len, data);
}
void   sys_rpc__settimeofday_request__free_unpacked
                     (SysRpc__SettimeofdayRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sys_rpc__settimeofday_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sys_rpc__settimeofday_response__init
                     (SysRpc__SettimeofdayResponse         *message)
{
  static const SysRpc__SettimeofdayResponse init_value = SYS_RPC__SETTIMEOFDAY_RESPONSE__INIT;
  *message = init_value;
}
size_t sys_rpc__settimeofday_response__get_packed_size
                     (const SysRpc__SettimeofdayResponse *message)
{
  assert(message->base.descriptor == &sys_rpc__settimeofday_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sys_rpc__settimeofday_response__pack
                     (const SysRpc__SettimeofdayResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sys_rpc__settimeofday_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sys_rpc__settimeofday_response__pack_to_buffer
                     (const SysRpc__SettimeofdayResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sys_rpc__settimeofday_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SysRpc__SettimeofdayResponse *
       sys_rpc__settimeofday_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SysRpc__SettimeofdayResponse *)
     protobuf_c_message_unpack (&sys_rpc__settimeofday_response__descriptor,
                                allocator, len, data);
}
void   sys_rpc__settimeofday_response__free_unpacked
                     (SysRpc__SettimeofdayResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sys_rpc__settimeofday_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sys_rpc__gettimeofday_response__timeval__init
                     (SysRpc__GettimeofdayResponse__Timeval         *message)
{
  static const SysRpc__GettimeofdayResponse__Timeval init_value = SYS_RPC__GETTIMEOFDAY_RESPONSE__TIMEVAL__INIT;
  *message = init_value;
}
void   sys_rpc__gettimeofday_response__timezone__init
                     (SysRpc__GettimeofdayResponse__Timezone         *message)
{
  static const SysRpc__GettimeofdayResponse__Timezone init_value = SYS_RPC__GETTIMEOFDAY_RESPONSE__TIMEZONE__INIT;
  *message = init_value;
}
void   sys_rpc__gettimeofday_response__gettimeofday_request_status__init
                     (SysRpc__GettimeofdayResponse__GettimeofdayRequestStatus         *message)
{
  static const SysRpc__GettimeofdayResponse__GettimeofdayRequestStatus init_value = SYS_RPC__GETTIMEOFDAY_RESPONSE__GETTIMEOFDAY_REQUEST_STATUS__INIT;
  *message = init_value;
}
void   sys_rpc__gettimeofday_response__init
                     (SysRpc__GettimeofdayResponse         *message)
{
  static const SysRpc__GettimeofdayResponse init_value = SYS_RPC__GETTIMEOFDAY_RESPONSE__INIT;
  *message = init_value;
}
size_t sys_rpc__gettimeofday_response__get_packed_size
                     (const SysRpc__GettimeofdayResponse *message)
{
  assert(message->base.descriptor == &sys_rpc__gettimeofday_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sys_rpc__gettimeofday_response__pack
                     (const SysRpc__GettimeofdayResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sys_rpc__gettimeofday_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sys_rpc__gettimeofday_response__pack_to_buffer
                     (const SysRpc__GettimeofdayResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sys_rpc__gettimeofday_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SysRpc__GettimeofdayResponse *
       sys_rpc__gettimeofday_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SysRpc__GettimeofdayResponse *)
     protobuf_c_message_unpack (&sys_rpc__gettimeofday_response__descriptor,
                                allocator, len, data);
}
void   sys_rpc__gettimeofday_response__free_unpacked
                     (SysRpc__GettimeofdayResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sys_rpc__gettimeofday_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sys_rpc__x_rpc_message__init
                     (SysRpc__XRPCMessage         *message)
{
  static const SysRpc__XRPCMessage init_value = SYS_RPC__X_RPC_MESSAGE__INIT;
  *message = init_value;
}
size_t sys_rpc__x_rpc_message__get_packed_size
                     (const SysRpc__XRPCMessage *message)
{
  assert(message->base.descriptor == &sys_rpc__x_rpc_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sys_rpc__x_rpc_message__pack
                     (const SysRpc__XRPCMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sys_rpc__x_rpc_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sys_rpc__x_rpc_message__pack_to_buffer
                     (const SysRpc__XRPCMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sys_rpc__x_rpc_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SysRpc__XRPCMessage *
       sys_rpc__x_rpc_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SysRpc__XRPCMessage *)
     protobuf_c_message_unpack (&sys_rpc__x_rpc_message__descriptor,
                                allocator, len, data);
}
void   sys_rpc__x_rpc_message__free_unpacked
                     (SysRpc__XRPCMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sys_rpc__x_rpc_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue sys_rpc__x_rpc_message_type__type__enum_values_by_number[2] =
{
  { "request", "SYS_RPC__X_RPC_MESSAGE_TYPE__TYPE__request", 0 },
  { "response", "SYS_RPC__X_RPC_MESSAGE_TYPE__TYPE__response", 1 },
};
static const ProtobufCIntRange sys_rpc__x_rpc_message_type__type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex sys_rpc__x_rpc_message_type__type__enum_values_by_name[2] =
{
  { "request", 0 },
  { "response", 1 },
};
const ProtobufCEnumDescriptor sys_rpc__x_rpc_message_type__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "sys_rpc.xRPC_message_type.Type",
  "Type",
  "SysRpc__XRPCMessageType__Type",
  "sys_rpc",
  2,
  sys_rpc__x_rpc_message_type__type__enum_values_by_number,
  2,
  sys_rpc__x_rpc_message_type__type__enum_values_by_name,
  1,
  sys_rpc__x_rpc_message_type__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue sys_rpc__x_rpc_message_type__procedure__enum_values_by_number[2] =
{
  { "settimeofday", "SYS_RPC__X_RPC_MESSAGE_TYPE__PROCEDURE__settimeofday", 0 },
  { "gettimeofday", "SYS_RPC__X_RPC_MESSAGE_TYPE__PROCEDURE__gettimeofday", 1 },
};
static const ProtobufCIntRange sys_rpc__x_rpc_message_type__procedure__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex sys_rpc__x_rpc_message_type__procedure__enum_values_by_name[2] =
{
  { "gettimeofday", 1 },
  { "settimeofday", 0 },
};
const ProtobufCEnumDescriptor sys_rpc__x_rpc_message_type__procedure__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "sys_rpc.xRPC_message_type.Procedure",
  "Procedure",
  "SysRpc__XRPCMessageType__Procedure",
  "sys_rpc",
  2,
  sys_rpc__x_rpc_message_type__procedure__enum_values_by_number,
  2,
  sys_rpc__x_rpc_message_type__procedure__enum_values_by_name,
  1,
  sys_rpc__x_rpc_message_type__procedure__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor sys_rpc__x_rpc_message_type__field_descriptors[2] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SysRpc__XRPCMessageType, type),
    &sys_rpc__x_rpc_message_type__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "procedure",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SysRpc__XRPCMessageType, procedure),
    &sys_rpc__x_rpc_message_type__procedure__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sys_rpc__x_rpc_message_type__field_indices_by_name[] = {
  1,   /* field[1] = procedure */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange sys_rpc__x_rpc_message_type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sys_rpc__x_rpc_message_type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sys_rpc.xRPC_message_type",
  "XRPCMessageType",
  "SysRpc__XRPCMessageType",
  "sys_rpc",
  sizeof(SysRpc__XRPCMessageType),
  2,
  sys_rpc__x_rpc_message_type__field_descriptors,
  sys_rpc__x_rpc_message_type__field_indices_by_name,
  1,  sys_rpc__x_rpc_message_type__number_ranges,
  (ProtobufCMessageInit) sys_rpc__x_rpc_message_type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sys_rpc__settimeofday_request__timeval__field_descriptors[2] =
{
  {
    "tv_sec",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SysRpc__SettimeofdayRequest__Timeval, tv_sec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tv_usec",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SysRpc__SettimeofdayRequest__Timeval, tv_usec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sys_rpc__settimeofday_request__timeval__field_indices_by_name[] = {
  0,   /* field[0] = tv_sec */
  1,   /* field[1] = tv_usec */
};
static const ProtobufCIntRange sys_rpc__settimeofday_request__timeval__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sys_rpc__settimeofday_request__timeval__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sys_rpc.settimeofdayRequest.timeval",
  "Timeval",
  "SysRpc__SettimeofdayRequest__Timeval",
  "sys_rpc",
  sizeof(SysRpc__SettimeofdayRequest__Timeval),
  2,
  sys_rpc__settimeofday_request__timeval__field_descriptors,
  sys_rpc__settimeofday_request__timeval__field_indices_by_name,
  1,  sys_rpc__settimeofday_request__timeval__number_ranges,
  (ProtobufCMessageInit) sys_rpc__settimeofday_request__timeval__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sys_rpc__settimeofday_request__timezone__field_descriptors[2] =
{
  {
    "tz_minuteswest",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SysRpc__SettimeofdayRequest__Timezone, tz_minuteswest),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tz_dsttime",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SysRpc__SettimeofdayRequest__Timezone, tz_dsttime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sys_rpc__settimeofday_request__timezone__field_indices_by_name[] = {
  1,   /* field[1] = tz_dsttime */
  0,   /* field[0] = tz_minuteswest */
};
static const ProtobufCIntRange sys_rpc__settimeofday_request__timezone__number_ranges[1 + 1] =
{
  { 3, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sys_rpc__settimeofday_request__timezone__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sys_rpc.settimeofdayRequest.timezone",
  "Timezone",
  "SysRpc__SettimeofdayRequest__Timezone",
  "sys_rpc",
  sizeof(SysRpc__SettimeofdayRequest__Timezone),
  2,
  sys_rpc__settimeofday_request__timezone__field_descriptors,
  sys_rpc__settimeofday_request__timezone__field_indices_by_name,
  1,  sys_rpc__settimeofday_request__timezone__number_ranges,
  (ProtobufCMessageInit) sys_rpc__settimeofday_request__timezone__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sys_rpc__settimeofday_request__field_descriptors[2] =
{
  {
    "timeval_s",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SysRpc__SettimeofdayRequest, timeval_s),
    &sys_rpc__settimeofday_request__timeval__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timezone_s",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SysRpc__SettimeofdayRequest, timezone_s),
    &sys_rpc__settimeofday_request__timezone__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sys_rpc__settimeofday_request__field_indices_by_name[] = {
  0,   /* field[0] = timeval_s */
  1,   /* field[1] = timezone_s */
};
static const ProtobufCIntRange sys_rpc__settimeofday_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sys_rpc__settimeofday_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sys_rpc.settimeofdayRequest",
  "SettimeofdayRequest",
  "SysRpc__SettimeofdayRequest",
  "sys_rpc",
  sizeof(SysRpc__SettimeofdayRequest),
  2,
  sys_rpc__settimeofday_request__field_descriptors,
  sys_rpc__settimeofday_request__field_indices_by_name,
  1,  sys_rpc__settimeofday_request__number_ranges,
  (ProtobufCMessageInit) sys_rpc__settimeofday_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sys_rpc__settimeofday_response__field_descriptors[2] =
{
  {
    "return_value",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(SysRpc__SettimeofdayResponse, return_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errno_alt",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(SysRpc__SettimeofdayResponse, errno_alt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sys_rpc__settimeofday_response__field_indices_by_name[] = {
  1,   /* field[1] = errno_alt */
  0,   /* field[0] = return_value */
};
static const ProtobufCIntRange sys_rpc__settimeofday_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sys_rpc__settimeofday_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sys_rpc.settimeofdayResponse",
  "SettimeofdayResponse",
  "SysRpc__SettimeofdayResponse",
  "sys_rpc",
  sizeof(SysRpc__SettimeofdayResponse),
  2,
  sys_rpc__settimeofday_response__field_descriptors,
  sys_rpc__settimeofday_response__field_indices_by_name,
  1,  sys_rpc__settimeofday_response__number_ranges,
  (ProtobufCMessageInit) sys_rpc__settimeofday_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sys_rpc__gettimeofday_response__timeval__field_descriptors[2] =
{
  {
    "tv_sec",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SysRpc__GettimeofdayResponse__Timeval, tv_sec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tv_usec",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SysRpc__GettimeofdayResponse__Timeval, tv_usec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sys_rpc__gettimeofday_response__timeval__field_indices_by_name[] = {
  0,   /* field[0] = tv_sec */
  1,   /* field[1] = tv_usec */
};
static const ProtobufCIntRange sys_rpc__gettimeofday_response__timeval__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sys_rpc__gettimeofday_response__timeval__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sys_rpc.gettimeofdayResponse.timeval",
  "Timeval",
  "SysRpc__GettimeofdayResponse__Timeval",
  "sys_rpc",
  sizeof(SysRpc__GettimeofdayResponse__Timeval),
  2,
  sys_rpc__gettimeofday_response__timeval__field_descriptors,
  sys_rpc__gettimeofday_response__timeval__field_indices_by_name,
  1,  sys_rpc__gettimeofday_response__timeval__number_ranges,
  (ProtobufCMessageInit) sys_rpc__gettimeofday_response__timeval__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sys_rpc__gettimeofday_response__timezone__field_descriptors[2] =
{
  {
    "tz_minuteswest",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SysRpc__GettimeofdayResponse__Timezone, tz_minuteswest),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tz_dsttime",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SysRpc__GettimeofdayResponse__Timezone, tz_dsttime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sys_rpc__gettimeofday_response__timezone__field_indices_by_name[] = {
  1,   /* field[1] = tz_dsttime */
  0,   /* field[0] = tz_minuteswest */
};
static const ProtobufCIntRange sys_rpc__gettimeofday_response__timezone__number_ranges[1 + 1] =
{
  { 3, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sys_rpc__gettimeofday_response__timezone__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sys_rpc.gettimeofdayResponse.timezone",
  "Timezone",
  "SysRpc__GettimeofdayResponse__Timezone",
  "sys_rpc",
  sizeof(SysRpc__GettimeofdayResponse__Timezone),
  2,
  sys_rpc__gettimeofday_response__timezone__field_descriptors,
  sys_rpc__gettimeofday_response__timezone__field_indices_by_name,
  1,  sys_rpc__gettimeofday_response__timezone__number_ranges,
  (ProtobufCMessageInit) sys_rpc__gettimeofday_response__timezone__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sys_rpc__gettimeofday_response__gettimeofday_request_status__field_descriptors[2] =
{
  {
    "return_value",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(SysRpc__GettimeofdayResponse__GettimeofdayRequestStatus, return_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errno_alt",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(SysRpc__GettimeofdayResponse__GettimeofdayRequestStatus, errno_alt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sys_rpc__gettimeofday_response__gettimeofday_request_status__field_indices_by_name[] = {
  1,   /* field[1] = errno_alt */
  0,   /* field[0] = return_value */
};
static const ProtobufCIntRange sys_rpc__gettimeofday_response__gettimeofday_request_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sys_rpc__gettimeofday_response__gettimeofday_request_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sys_rpc.gettimeofdayResponse.gettimeofdayRequestStatus",
  "GettimeofdayRequestStatus",
  "SysRpc__GettimeofdayResponse__GettimeofdayRequestStatus",
  "sys_rpc",
  sizeof(SysRpc__GettimeofdayResponse__GettimeofdayRequestStatus),
  2,
  sys_rpc__gettimeofday_response__gettimeofday_request_status__field_descriptors,
  sys_rpc__gettimeofday_response__gettimeofday_request_status__field_indices_by_name,
  1,  sys_rpc__gettimeofday_response__gettimeofday_request_status__number_ranges,
  (ProtobufCMessageInit) sys_rpc__gettimeofday_response__gettimeofday_request_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sys_rpc__gettimeofday_response__field_descriptors[3] =
{
  {
    "timeval_r",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SysRpc__GettimeofdayResponse, timeval_r),
    &sys_rpc__gettimeofday_response__timeval__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timezone_r",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SysRpc__GettimeofdayResponse, timezone_r),
    &sys_rpc__gettimeofday_response__timezone__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SysRpc__GettimeofdayResponse, status),
    &sys_rpc__gettimeofday_response__gettimeofday_request_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sys_rpc__gettimeofday_response__field_indices_by_name[] = {
  2,   /* field[2] = status */
  0,   /* field[0] = timeval_r */
  1,   /* field[1] = timezone_r */
};
static const ProtobufCIntRange sys_rpc__gettimeofday_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor sys_rpc__gettimeofday_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sys_rpc.gettimeofdayResponse",
  "GettimeofdayResponse",
  "SysRpc__GettimeofdayResponse",
  "sys_rpc",
  sizeof(SysRpc__GettimeofdayResponse),
  3,
  sys_rpc__gettimeofday_response__field_descriptors,
  sys_rpc__gettimeofday_response__field_indices_by_name,
  1,  sys_rpc__gettimeofday_response__number_ranges,
  (ProtobufCMessageInit) sys_rpc__gettimeofday_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sys_rpc__x_rpc_message__field_descriptors[4] =
{
  {
    "mes_type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SysRpc__XRPCMessage, mes_type),
    &sys_rpc__x_rpc_message_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "setTimeRequest",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SysRpc__XRPCMessage, settimerequest),
    &sys_rpc__settimeofday_request__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "setTimeResponse",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SysRpc__XRPCMessage, settimeresponse),
    &sys_rpc__settimeofday_response__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "getTimeResponse",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SysRpc__XRPCMessage, gettimeresponse),
    &sys_rpc__gettimeofday_response__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sys_rpc__x_rpc_message__field_indices_by_name[] = {
  3,   /* field[3] = getTimeResponse */
  0,   /* field[0] = mes_type */
  1,   /* field[1] = setTimeRequest */
  2,   /* field[2] = setTimeResponse */
};
static const ProtobufCIntRange sys_rpc__x_rpc_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor sys_rpc__x_rpc_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sys_rpc.xRPC_message",
  "XRPCMessage",
  "SysRpc__XRPCMessage",
  "sys_rpc",
  sizeof(SysRpc__XRPCMessage),
  4,
  sys_rpc__x_rpc_message__field_descriptors,
  sys_rpc__x_rpc_message__field_indices_by_name,
  1,  sys_rpc__x_rpc_message__number_ranges,
  (ProtobufCMessageInit) sys_rpc__x_rpc_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
