# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messagefile.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messagefile.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x11messagefile.proto\"*\n\x07TimeVal\x12\x0e\n\x06tv_sec\x18\x01 \x01(\r\x12\x0f\n\x07tv_usec\x18\x02 \x01(\r\"0\n\x13SettimeofdayRequest\x12\x19\n\x07timeval\x18\x01 \x01(\x0b\x32\x08.TimeVal\";\n\x14SettimeofdayResponse\x12\x14\n\x0creturn_value\x18\x01 \x01(\x11\x12\r\n\x05\x65rrno\x18\x02 \x01(\x11\"#\n\x13GettimeofdayRequest\x12\x0c\n\x04stub\x18\x01 \x01(\x05\"V\n\x14GettimeofdayResponse\x12\x14\n\x0creturn_value\x18\x01 \x01(\x11\x12\r\n\x05\x65rrno\x18\x02 \x01(\x11\x12\x19\n\x07timeval\x18\x03 \x01(\x0b\x32\x08.TimeVal\"\x84\x01\n\x07Request\x12\x34\n\x14settimeofday_request\x18\x01 \x01(\x0b\x32\x14.SettimeofdayRequestH\x00\x12\x34\n\x14gettimeofday_request\x18\x02 \x01(\x0b\x32\x14.GettimeofdayRequestH\x00\x42\r\n\x0bRequestFunc\"\x8a\x01\n\x08Response\x12\x36\n\x15settimeofday_response\x18\x01 \x01(\x0b\x32\x15.SettimeofdayResponseH\x00\x12\x36\n\x15gettimeofday_response\x18\x02 \x01(\x0b\x32\x15.GettimeofdayResponseH\x00\x42\x0e\n\x0cResponseFunc\"v\n\x0bxRPCMessage\x12\x1b\n\x07request\x18\x01 \x01(\x0b\x32\x08.RequestH\x00\x12\x1d\n\x08response\x18\x02 \x01(\x0b\x32\t.ResponseH\x00\x12\x1c\n\ntime_stamp\x18\x03 \x01(\x0b\x32\x08.TimeValB\r\n\x0bMessageTypeb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TIMEVAL = _descriptor.Descriptor(
  name='TimeVal',
  full_name='TimeVal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tv_sec', full_name='TimeVal.tv_sec', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tv_usec', full_name='TimeVal.tv_usec', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=63,
)


_SETTIMEOFDAYREQUEST = _descriptor.Descriptor(
  name='SettimeofdayRequest',
  full_name='SettimeofdayRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeval', full_name='SettimeofdayRequest.timeval', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=113,
)


_SETTIMEOFDAYRESPONSE = _descriptor.Descriptor(
  name='SettimeofdayResponse',
  full_name='SettimeofdayResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='return_value', full_name='SettimeofdayResponse.return_value', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errno', full_name='SettimeofdayResponse.errno', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=174,
)


_GETTIMEOFDAYREQUEST = _descriptor.Descriptor(
  name='GettimeofdayRequest',
  full_name='GettimeofdayRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stub', full_name='GettimeofdayRequest.stub', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=211,
)


_GETTIMEOFDAYRESPONSE = _descriptor.Descriptor(
  name='GettimeofdayResponse',
  full_name='GettimeofdayResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='return_value', full_name='GettimeofdayResponse.return_value', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errno', full_name='GettimeofdayResponse.errno', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timeval', full_name='GettimeofdayResponse.timeval', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=299,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='settimeofday_request', full_name='Request.settimeofday_request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gettimeofday_request', full_name='Request.gettimeofday_request', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='RequestFunc', full_name='Request.RequestFunc',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=302,
  serialized_end=434,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='settimeofday_response', full_name='Response.settimeofday_response', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gettimeofday_response', full_name='Response.gettimeofday_response', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='ResponseFunc', full_name='Response.ResponseFunc',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=437,
  serialized_end=575,
)


_XRPCMESSAGE = _descriptor.Descriptor(
  name='xRPCMessage',
  full_name='xRPCMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='xRPCMessage.request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='response', full_name='xRPCMessage.response', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='xRPCMessage.time_stamp', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='MessageType', full_name='xRPCMessage.MessageType',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=577,
  serialized_end=695,
)

_SETTIMEOFDAYREQUEST.fields_by_name['timeval'].message_type = _TIMEVAL
_GETTIMEOFDAYRESPONSE.fields_by_name['timeval'].message_type = _TIMEVAL
_REQUEST.fields_by_name['settimeofday_request'].message_type = _SETTIMEOFDAYREQUEST
_REQUEST.fields_by_name['gettimeofday_request'].message_type = _GETTIMEOFDAYREQUEST
_REQUEST.oneofs_by_name['RequestFunc'].fields.append(
  _REQUEST.fields_by_name['settimeofday_request'])
_REQUEST.fields_by_name['settimeofday_request'].containing_oneof = _REQUEST.oneofs_by_name['RequestFunc']
_REQUEST.oneofs_by_name['RequestFunc'].fields.append(
  _REQUEST.fields_by_name['gettimeofday_request'])
_REQUEST.fields_by_name['gettimeofday_request'].containing_oneof = _REQUEST.oneofs_by_name['RequestFunc']
_RESPONSE.fields_by_name['settimeofday_response'].message_type = _SETTIMEOFDAYRESPONSE
_RESPONSE.fields_by_name['gettimeofday_response'].message_type = _GETTIMEOFDAYRESPONSE
_RESPONSE.oneofs_by_name['ResponseFunc'].fields.append(
  _RESPONSE.fields_by_name['settimeofday_response'])
_RESPONSE.fields_by_name['settimeofday_response'].containing_oneof = _RESPONSE.oneofs_by_name['ResponseFunc']
_RESPONSE.oneofs_by_name['ResponseFunc'].fields.append(
  _RESPONSE.fields_by_name['gettimeofday_response'])
_RESPONSE.fields_by_name['gettimeofday_response'].containing_oneof = _RESPONSE.oneofs_by_name['ResponseFunc']
_XRPCMESSAGE.fields_by_name['request'].message_type = _REQUEST
_XRPCMESSAGE.fields_by_name['response'].message_type = _RESPONSE
_XRPCMESSAGE.fields_by_name['time_stamp'].message_type = _TIMEVAL
_XRPCMESSAGE.oneofs_by_name['MessageType'].fields.append(
  _XRPCMESSAGE.fields_by_name['request'])
_XRPCMESSAGE.fields_by_name['request'].containing_oneof = _XRPCMESSAGE.oneofs_by_name['MessageType']
_XRPCMESSAGE.oneofs_by_name['MessageType'].fields.append(
  _XRPCMESSAGE.fields_by_name['response'])
_XRPCMESSAGE.fields_by_name['response'].containing_oneof = _XRPCMESSAGE.oneofs_by_name['MessageType']
DESCRIPTOR.message_types_by_name['TimeVal'] = _TIMEVAL
DESCRIPTOR.message_types_by_name['SettimeofdayRequest'] = _SETTIMEOFDAYREQUEST
DESCRIPTOR.message_types_by_name['SettimeofdayResponse'] = _SETTIMEOFDAYRESPONSE
DESCRIPTOR.message_types_by_name['GettimeofdayRequest'] = _GETTIMEOFDAYREQUEST
DESCRIPTOR.message_types_by_name['GettimeofdayResponse'] = _GETTIMEOFDAYRESPONSE
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['xRPCMessage'] = _XRPCMESSAGE

TimeVal = _reflection.GeneratedProtocolMessageType('TimeVal', (_message.Message,), dict(
  DESCRIPTOR = _TIMEVAL,
  __module__ = 'messagefile_pb2'
  # @@protoc_insertion_point(class_scope:TimeVal)
  ))
_sym_db.RegisterMessage(TimeVal)

SettimeofdayRequest = _reflection.GeneratedProtocolMessageType('SettimeofdayRequest', (_message.Message,), dict(
  DESCRIPTOR = _SETTIMEOFDAYREQUEST,
  __module__ = 'messagefile_pb2'
  # @@protoc_insertion_point(class_scope:SettimeofdayRequest)
  ))
_sym_db.RegisterMessage(SettimeofdayRequest)

SettimeofdayResponse = _reflection.GeneratedProtocolMessageType('SettimeofdayResponse', (_message.Message,), dict(
  DESCRIPTOR = _SETTIMEOFDAYRESPONSE,
  __module__ = 'messagefile_pb2'
  # @@protoc_insertion_point(class_scope:SettimeofdayResponse)
  ))
_sym_db.RegisterMessage(SettimeofdayResponse)

GettimeofdayRequest = _reflection.GeneratedProtocolMessageType('GettimeofdayRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETTIMEOFDAYREQUEST,
  __module__ = 'messagefile_pb2'
  # @@protoc_insertion_point(class_scope:GettimeofdayRequest)
  ))
_sym_db.RegisterMessage(GettimeofdayRequest)

GettimeofdayResponse = _reflection.GeneratedProtocolMessageType('GettimeofdayResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETTIMEOFDAYRESPONSE,
  __module__ = 'messagefile_pb2'
  # @@protoc_insertion_point(class_scope:GettimeofdayResponse)
  ))
_sym_db.RegisterMessage(GettimeofdayResponse)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'messagefile_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'messagefile_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  ))
_sym_db.RegisterMessage(Response)

xRPCMessage = _reflection.GeneratedProtocolMessageType('xRPCMessage', (_message.Message,), dict(
  DESCRIPTOR = _XRPCMESSAGE,
  __module__ = 'messagefile_pb2'
  # @@protoc_insertion_point(class_scope:xRPCMessage)
  ))
_sym_db.RegisterMessage(xRPCMessage)


# @@protoc_insertion_point(module_scope)
