# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: syscallprot.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='syscallprot.proto',
  package='sys_rpc',
  syntax='proto3',
  serialized_pb=_b('\n\x11syscallprot.proto\x12\x07sys_rpc\"\xcf\x01\n\x11xRPC_message_type\x12-\n\x04type\x18\x01 \x01(\x0e\x32\x1f.sys_rpc.xRPC_message_type.Type\x12\x37\n\tprocedure\x18\x02 \x01(\x0e\x32$.sys_rpc.xRPC_message_type.Procedure\"!\n\x04Type\x12\x0b\n\x07request\x10\x00\x12\x0c\n\x08response\x10\x01\"/\n\tProcedure\x12\x10\n\x0csettimeofday\x10\x00\x12\x10\n\x0cgettimeofday\x10\x01\"z\n\x13settimeofdayRequest\x12\x37\n\ttimeval_s\x18\x01 \x01(\x0b\x32$.sys_rpc.settimeofdayRequest.timeval\x1a*\n\x07timeval\x12\x0e\n\x06tv_sec\x18\x01 \x01(\r\x12\x0f\n\x07tv_usec\x18\x02 \x01(\r\"?\n\x14settimeofdayResponse\x12\x14\n\x0creturn_value\x18\x01 \x01(\x11\x12\x11\n\terrno_alt\x18\x02 \x01(\x11\"\x8b\x02\n\x14gettimeofdayResponse\x12\x38\n\ttimeval_r\x18\x01 \x01(\x0b\x32%.sys_rpc.gettimeofdayResponse.timeval\x12G\n\x06status\x18\x02 \x01(\x0b\x32\x37.sys_rpc.gettimeofdayResponse.gettimeofdayRequestStatus\x1a*\n\x07timeval\x12\x0e\n\x06tv_sec\x18\x01 \x01(\r\x12\x0f\n\x07tv_usec\x18\x02 \x01(\r\x1a\x44\n\x19gettimeofdayRequestStatus\x12\x14\n\x0creturn_value\x18\x01 \x01(\x11\x12\x11\n\terrno_alt\x18\x02 \x01(\x11\"\xe2\x01\n\x0cxRPC_message\x12,\n\x08mes_type\x18\x01 \x01(\x0b\x32\x1a.sys_rpc.xRPC_message_type\x12\x34\n\x0esetTimeRequest\x18\x02 \x01(\x0b\x32\x1c.sys_rpc.settimeofdayRequest\x12\x36\n\x0fsetTimeResponse\x18\x03 \x01(\x0b\x32\x1d.sys_rpc.settimeofdayResponse\x12\x36\n\x0fgetTimeResponse\x18\x04 \x01(\x0b\x32\x1d.sys_rpc.gettimeofdayResponseb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_XRPC_MESSAGE_TYPE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='sys_rpc.xRPC_message_type.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='request', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='response', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=156,
  serialized_end=189,
)
_sym_db.RegisterEnumDescriptor(_XRPC_MESSAGE_TYPE_TYPE)

_XRPC_MESSAGE_TYPE_PROCEDURE = _descriptor.EnumDescriptor(
  name='Procedure',
  full_name='sys_rpc.xRPC_message_type.Procedure',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='settimeofday', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='gettimeofday', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=191,
  serialized_end=238,
)
_sym_db.RegisterEnumDescriptor(_XRPC_MESSAGE_TYPE_PROCEDURE)


_XRPC_MESSAGE_TYPE = _descriptor.Descriptor(
  name='xRPC_message_type',
  full_name='sys_rpc.xRPC_message_type',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='sys_rpc.xRPC_message_type.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='procedure', full_name='sys_rpc.xRPC_message_type.procedure', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _XRPC_MESSAGE_TYPE_TYPE,
    _XRPC_MESSAGE_TYPE_PROCEDURE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=238,
)


_SETTIMEOFDAYREQUEST_TIMEVAL = _descriptor.Descriptor(
  name='timeval',
  full_name='sys_rpc.settimeofdayRequest.timeval',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tv_sec', full_name='sys_rpc.settimeofdayRequest.timeval.tv_sec', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tv_usec', full_name='sys_rpc.settimeofdayRequest.timeval.tv_usec', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=320,
  serialized_end=362,
)

_SETTIMEOFDAYREQUEST = _descriptor.Descriptor(
  name='settimeofdayRequest',
  full_name='sys_rpc.settimeofdayRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeval_s', full_name='sys_rpc.settimeofdayRequest.timeval_s', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SETTIMEOFDAYREQUEST_TIMEVAL, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=362,
)


_SETTIMEOFDAYRESPONSE = _descriptor.Descriptor(
  name='settimeofdayResponse',
  full_name='sys_rpc.settimeofdayResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='return_value', full_name='sys_rpc.settimeofdayResponse.return_value', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errno_alt', full_name='sys_rpc.settimeofdayResponse.errno_alt', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=364,
  serialized_end=427,
)


_GETTIMEOFDAYRESPONSE_TIMEVAL = _descriptor.Descriptor(
  name='timeval',
  full_name='sys_rpc.gettimeofdayResponse.timeval',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tv_sec', full_name='sys_rpc.gettimeofdayResponse.timeval.tv_sec', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tv_usec', full_name='sys_rpc.gettimeofdayResponse.timeval.tv_usec', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=320,
  serialized_end=362,
)

_GETTIMEOFDAYRESPONSE_GETTIMEOFDAYREQUESTSTATUS = _descriptor.Descriptor(
  name='gettimeofdayRequestStatus',
  full_name='sys_rpc.gettimeofdayResponse.gettimeofdayRequestStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='return_value', full_name='sys_rpc.gettimeofdayResponse.gettimeofdayRequestStatus.return_value', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errno_alt', full_name='sys_rpc.gettimeofdayResponse.gettimeofdayRequestStatus.errno_alt', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=629,
  serialized_end=697,
)

_GETTIMEOFDAYRESPONSE = _descriptor.Descriptor(
  name='gettimeofdayResponse',
  full_name='sys_rpc.gettimeofdayResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeval_r', full_name='sys_rpc.gettimeofdayResponse.timeval_r', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='sys_rpc.gettimeofdayResponse.status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_GETTIMEOFDAYRESPONSE_TIMEVAL, _GETTIMEOFDAYRESPONSE_GETTIMEOFDAYREQUESTSTATUS, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=430,
  serialized_end=697,
)


_XRPC_MESSAGE = _descriptor.Descriptor(
  name='xRPC_message',
  full_name='sys_rpc.xRPC_message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mes_type', full_name='sys_rpc.xRPC_message.mes_type', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='setTimeRequest', full_name='sys_rpc.xRPC_message.setTimeRequest', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='setTimeResponse', full_name='sys_rpc.xRPC_message.setTimeResponse', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='getTimeResponse', full_name='sys_rpc.xRPC_message.getTimeResponse', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=700,
  serialized_end=926,
)

_XRPC_MESSAGE_TYPE.fields_by_name['type'].enum_type = _XRPC_MESSAGE_TYPE_TYPE
_XRPC_MESSAGE_TYPE.fields_by_name['procedure'].enum_type = _XRPC_MESSAGE_TYPE_PROCEDURE
_XRPC_MESSAGE_TYPE_TYPE.containing_type = _XRPC_MESSAGE_TYPE
_XRPC_MESSAGE_TYPE_PROCEDURE.containing_type = _XRPC_MESSAGE_TYPE
_SETTIMEOFDAYREQUEST_TIMEVAL.containing_type = _SETTIMEOFDAYREQUEST
_SETTIMEOFDAYREQUEST.fields_by_name['timeval_s'].message_type = _SETTIMEOFDAYREQUEST_TIMEVAL
_GETTIMEOFDAYRESPONSE_TIMEVAL.containing_type = _GETTIMEOFDAYRESPONSE
_GETTIMEOFDAYRESPONSE_GETTIMEOFDAYREQUESTSTATUS.containing_type = _GETTIMEOFDAYRESPONSE
_GETTIMEOFDAYRESPONSE.fields_by_name['timeval_r'].message_type = _GETTIMEOFDAYRESPONSE_TIMEVAL
_GETTIMEOFDAYRESPONSE.fields_by_name['status'].message_type = _GETTIMEOFDAYRESPONSE_GETTIMEOFDAYREQUESTSTATUS
_XRPC_MESSAGE.fields_by_name['mes_type'].message_type = _XRPC_MESSAGE_TYPE
_XRPC_MESSAGE.fields_by_name['setTimeRequest'].message_type = _SETTIMEOFDAYREQUEST
_XRPC_MESSAGE.fields_by_name['setTimeResponse'].message_type = _SETTIMEOFDAYRESPONSE
_XRPC_MESSAGE.fields_by_name['getTimeResponse'].message_type = _GETTIMEOFDAYRESPONSE
DESCRIPTOR.message_types_by_name['xRPC_message_type'] = _XRPC_MESSAGE_TYPE
DESCRIPTOR.message_types_by_name['settimeofdayRequest'] = _SETTIMEOFDAYREQUEST
DESCRIPTOR.message_types_by_name['settimeofdayResponse'] = _SETTIMEOFDAYRESPONSE
DESCRIPTOR.message_types_by_name['gettimeofdayResponse'] = _GETTIMEOFDAYRESPONSE
DESCRIPTOR.message_types_by_name['xRPC_message'] = _XRPC_MESSAGE

xRPC_message_type = _reflection.GeneratedProtocolMessageType('xRPC_message_type', (_message.Message,), dict(
  DESCRIPTOR = _XRPC_MESSAGE_TYPE,
  __module__ = 'syscallprot_pb2'
  # @@protoc_insertion_point(class_scope:sys_rpc.xRPC_message_type)
  ))
_sym_db.RegisterMessage(xRPC_message_type)

settimeofdayRequest = _reflection.GeneratedProtocolMessageType('settimeofdayRequest', (_message.Message,), dict(

  timeval = _reflection.GeneratedProtocolMessageType('timeval', (_message.Message,), dict(
    DESCRIPTOR = _SETTIMEOFDAYREQUEST_TIMEVAL,
    __module__ = 'syscallprot_pb2'
    # @@protoc_insertion_point(class_scope:sys_rpc.settimeofdayRequest.timeval)
    ))
  ,
  DESCRIPTOR = _SETTIMEOFDAYREQUEST,
  __module__ = 'syscallprot_pb2'
  # @@protoc_insertion_point(class_scope:sys_rpc.settimeofdayRequest)
  ))
_sym_db.RegisterMessage(settimeofdayRequest)
_sym_db.RegisterMessage(settimeofdayRequest.timeval)

settimeofdayResponse = _reflection.GeneratedProtocolMessageType('settimeofdayResponse', (_message.Message,), dict(
  DESCRIPTOR = _SETTIMEOFDAYRESPONSE,
  __module__ = 'syscallprot_pb2'
  # @@protoc_insertion_point(class_scope:sys_rpc.settimeofdayResponse)
  ))
_sym_db.RegisterMessage(settimeofdayResponse)

gettimeofdayResponse = _reflection.GeneratedProtocolMessageType('gettimeofdayResponse', (_message.Message,), dict(

  timeval = _reflection.GeneratedProtocolMessageType('timeval', (_message.Message,), dict(
    DESCRIPTOR = _GETTIMEOFDAYRESPONSE_TIMEVAL,
    __module__ = 'syscallprot_pb2'
    # @@protoc_insertion_point(class_scope:sys_rpc.gettimeofdayResponse.timeval)
    ))
  ,

  gettimeofdayRequestStatus = _reflection.GeneratedProtocolMessageType('gettimeofdayRequestStatus', (_message.Message,), dict(
    DESCRIPTOR = _GETTIMEOFDAYRESPONSE_GETTIMEOFDAYREQUESTSTATUS,
    __module__ = 'syscallprot_pb2'
    # @@protoc_insertion_point(class_scope:sys_rpc.gettimeofdayResponse.gettimeofdayRequestStatus)
    ))
  ,
  DESCRIPTOR = _GETTIMEOFDAYRESPONSE,
  __module__ = 'syscallprot_pb2'
  # @@protoc_insertion_point(class_scope:sys_rpc.gettimeofdayResponse)
  ))
_sym_db.RegisterMessage(gettimeofdayResponse)
_sym_db.RegisterMessage(gettimeofdayResponse.timeval)
_sym_db.RegisterMessage(gettimeofdayResponse.gettimeofdayRequestStatus)

xRPC_message = _reflection.GeneratedProtocolMessageType('xRPC_message', (_message.Message,), dict(
  DESCRIPTOR = _XRPC_MESSAGE,
  __module__ = 'syscallprot_pb2'
  # @@protoc_insertion_point(class_scope:sys_rpc.xRPC_message)
  ))
_sym_db.RegisterMessage(xRPC_message)


# @@protoc_insertion_point(module_scope)
